name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Alsa Sound
      run: sudo apt-get install libasound2-dev

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly

    - name: Cargo Build
      run: cargo +nightly build

    - name: Cargo Test
      run: cargo +nightly test
